server:
  port: 8889
  servlet:
    context-path: /mongo


spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/ngy
#      todo auth=false ğŸ‘‡ä¸‹é¢å¯ä»¥ä¸å¡«
#      username: your_username
#      password: your_password